// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestOrdersStatus.proto

#ifndef PROTOBUF_RequestOrdersStatus_2eproto__INCLUDED
#define PROTOBUF_RequestOrdersStatus_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ProtoTypes {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RequestOrdersStatus_2eproto();
void protobuf_AssignDesc_RequestOrdersStatus_2eproto();
void protobuf_ShutdownFile_RequestOrdersStatus_2eproto();

class OrdersStatusRequest;

// ===================================================================

class OrdersStatusRequest : public ::google::protobuf::Message {
 public:
  OrdersStatusRequest();
  virtual ~OrdersStatusRequest();

  OrdersStatusRequest(const OrdersStatusRequest& from);

  inline OrdersStatusRequest& operator=(const OrdersStatusRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OrdersStatusRequest& default_instance();

  void Swap(OrdersStatusRequest* other);

  // implements Message ----------------------------------------------

  OrdersStatusRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OrdersStatusRequest& from);
  void MergeFrom(const OrdersStatusRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 logins = 1;
  inline int logins_size() const;
  inline void clear_logins();
  static const int kLoginsFieldNumber = 1;
  inline ::google::protobuf::int32 logins(int index) const;
  inline void set_logins(int index, ::google::protobuf::int32 value);
  inline void add_logins(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      logins() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_logins();

  // @@protoc_insertion_point(class_scope:ProtoTypes.OrdersStatusRequest)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > logins_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_RequestOrdersStatus_2eproto();
  friend void protobuf_AssignDesc_RequestOrdersStatus_2eproto();
  friend void protobuf_ShutdownFile_RequestOrdersStatus_2eproto();

  void InitAsDefaultInstance();
  static OrdersStatusRequest* default_instance_;
};
// ===================================================================


// ===================================================================

// OrdersStatusRequest

// repeated int32 logins = 1;
inline int OrdersStatusRequest::logins_size() const {
  return logins_.size();
}
inline void OrdersStatusRequest::clear_logins() {
  logins_.Clear();
}
inline ::google::protobuf::int32 OrdersStatusRequest::logins(int index) const {
  return logins_.Get(index);
}
inline void OrdersStatusRequest::set_logins(int index, ::google::protobuf::int32 value) {
  logins_.Set(index, value);
}
inline void OrdersStatusRequest::add_logins(::google::protobuf::int32 value) {
  logins_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
OrdersStatusRequest::logins() const {
  return logins_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
OrdersStatusRequest::mutable_logins() {
  return &logins_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtoTypes

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RequestOrdersStatus_2eproto__INCLUDED
