//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RequestOrdersStatus.proto

using System;
using System.Collections.Generic;
using ProtoBuf;

namespace ProtoTypes
{
  [Serializable, ProtoContract(Name=@"OrdersStatusRequest")]
  public partial class OrdersStatusRequest : IExtensible
  {
    public OrdersStatusRequest() {}
    
    private readonly List<int> _logins = new List<int>();
    [ProtoMember(1, Name=@"logins", DataFormat = DataFormat.TwosComplement)]
    public List<int> logins
    {
      get { return _logins; }
    }
  
    private IExtension extensionObject;
    IExtension IExtensible.GetExtensionObject(bool createIfMissing)
      { return Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}