//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RequestExecution.proto
// Note: requires additional types generated from: SignalMT4Trade.proto
// Note: requires additional types generated from: Signal.proto

using System;
using System.Collections.Generic;
using System.ComponentModel;
using ProtoBuf;

namespace ProtoTypes
{
  [Serializable, ProtoContract(Name=@"ExecutionOrder")]
  public partial class ExecutionOrder : IExtensible
  {
    public ExecutionOrder() {}
    
    private int _Login;
    [ProtoMember(1, IsRequired = true, Name=@"Login", DataFormat = DataFormat.TwosComplement)]
    public int Login
    {
      get { return _Login; }
      set { _Login = value; }
    }
    private ActionType _ActionType;
    [ProtoMember(2, IsRequired = true, Name=@"ActionType", DataFormat = DataFormat.TwosComplement)]
    public ActionType ActionType
    {
      get { return _ActionType; }
      set { _ActionType = value; }
    }
    private TradeSide _Side;
    [ProtoMember(3, IsRequired = true, Name=@"Side", DataFormat = DataFormat.TwosComplement)]
    public TradeSide Side
    {
      get { return _Side; }
      set { _Side = value; }
    }
    private double _Volume;
    [ProtoMember(4, IsRequired = true, Name=@"Volume", DataFormat = DataFormat.TwosComplement)]
    public double Volume
    {
      get { return _Volume; }
      set { _Volume = value; }
    }
    private string _Symbol;
    [ProtoMember(5, IsRequired = true, Name=@"Symbol", DataFormat = DataFormat.Default)]
    public string Symbol
    {
      get { return _Symbol; }
      set { _Symbol = value; }
    }
    private int _OrderID = default(int);
    [ProtoMember(6, IsRequired = false, Name=@"OrderID", DataFormat = DataFormat.TwosComplement)]
    [DefaultValue(default(int))]
    public int OrderID
    {
      get { return _OrderID; }
      set { _OrderID = value; }
    }
    private double _Commission = default(double);
    [ProtoMember(7, IsRequired = false, Name=@"Commission", DataFormat = DataFormat.TwosComplement)]
    [DefaultValue(default(double))]
    public double Commission
    {
      get { return _Commission; }
      set { _Commission = value; }
    }
    private IExtension extensionObject;
    IExtension IExtensible.GetExtensionObject(bool createIfMissing)
      { return Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [Serializable, ProtoContract(Name=@"ExecutionSignal")]
  public partial class ExecutionSignal : IExtensible
  {
    public ExecutionSignal() {}
    
    private string _Comment;
    [ProtoMember(1, IsRequired = true, Name=@"Comment", DataFormat = DataFormat.Default)]
    public string Comment
    {
      get { return _Comment; }
      set { _Comment = value; }
    }
    private string _Destination;
    [ProtoMember(2, IsRequired = true, Name=@"Destination", DataFormat = DataFormat.Default)]
    public string Destination
    {
      get { return _Destination; }
      set { _Destination = value; }
    }
    private readonly List<ExecutionOrder> _Orders = new List<ExecutionOrder>();
    [ProtoMember(3, Name=@"Orders", DataFormat = DataFormat.Default)]
    public List<ExecutionOrder> Orders
    {
      get { return _Orders; }
    }
  
    private IExtension extensionObject;
    IExtension IExtensible.GetExtensionObject(bool createIfMissing)
      { return Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}