//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Request.proto

using System;
using System.ComponentModel;
using ProtoBuf;

namespace ProtoTypes
{
  [Serializable, ProtoContract(Name=@"Request")]
  public partial class Request : IExtensible
  {
    public Request() {}
    
    private RequestType _requestType;
    [ProtoMember(1, IsRequired = true, Name=@"requestType", DataFormat = DataFormat.TwosComplement)]
    public RequestType requestType
    {
      get { return _requestType; }
      set { _requestType = value; }
    }
    private string _destination;
    [ProtoMember(2, IsRequired = true, Name=@"destination", DataFormat = DataFormat.Default)]
    public string destination
    {
      get { return _destination; }
      set { _destination = value; }
    }
    private byte[] _Content = null;
    [ProtoMember(3, IsRequired = false, Name=@"Content", DataFormat = DataFormat.Default)]
    [DefaultValue(null)]
    public byte[] Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private IExtension extensionObject;
    IExtension IExtensible.GetExtensionObject(bool createIfMissing)
      { return Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [ProtoContract(Name=@"RequestType")]
    public enum RequestType
    {
            
      [ProtoEnum(Name=@"OrderStatusRequestType", Value=1)]
      OrderStatusRequestType = 1,
            
      [ProtoEnum(Name=@"ExecutionRequestType", Value=2)]
      ExecutionRequestType = 2,
            
      [ProtoEnum(Name=@"Connected", Value=3)]
      Connected = 3
    }
  
}