// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestOrdersStatus.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "RequestOrdersStatus.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ProtoTypes {

namespace {

const ::google::protobuf::Descriptor* OrdersStatusRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  OrdersStatusRequest_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_RequestOrdersStatus_2eproto() {
  protobuf_AddDesc_RequestOrdersStatus_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "RequestOrdersStatus.proto");
  GOOGLE_CHECK(file != NULL);
  OrdersStatusRequest_descriptor_ = file->message_type(0);
  static const int OrdersStatusRequest_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OrdersStatusRequest, logins_),
  };
  OrdersStatusRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      OrdersStatusRequest_descriptor_,
      OrdersStatusRequest::default_instance_,
      OrdersStatusRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OrdersStatusRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OrdersStatusRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(OrdersStatusRequest));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_RequestOrdersStatus_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    OrdersStatusRequest_descriptor_, &OrdersStatusRequest::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_RequestOrdersStatus_2eproto() {
  delete OrdersStatusRequest::default_instance_;
  delete OrdersStatusRequest_reflection_;
}

void protobuf_AddDesc_RequestOrdersStatus_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\031RequestOrdersStatus.proto\022\nProtoTypes\""
    "%\n\023OrdersStatusRequest\022\016\n\006logins\030\001 \003(\005", 78);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "RequestOrdersStatus.proto", &protobuf_RegisterTypes);
  OrdersStatusRequest::default_instance_ = new OrdersStatusRequest();
  OrdersStatusRequest::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_RequestOrdersStatus_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_RequestOrdersStatus_2eproto {
  StaticDescriptorInitializer_RequestOrdersStatus_2eproto() {
    protobuf_AddDesc_RequestOrdersStatus_2eproto();
  }
} static_descriptor_initializer_RequestOrdersStatus_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int OrdersStatusRequest::kLoginsFieldNumber;
#endif  // !_MSC_VER

OrdersStatusRequest::OrdersStatusRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void OrdersStatusRequest::InitAsDefaultInstance() {
}

OrdersStatusRequest::OrdersStatusRequest(const OrdersStatusRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void OrdersStatusRequest::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

OrdersStatusRequest::~OrdersStatusRequest() {
  SharedDtor();
}

void OrdersStatusRequest::SharedDtor() {
  if (this != default_instance_) {
  }
}

void OrdersStatusRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OrdersStatusRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return OrdersStatusRequest_descriptor_;
}

const OrdersStatusRequest& OrdersStatusRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_RequestOrdersStatus_2eproto();
  return *default_instance_;
}

OrdersStatusRequest* OrdersStatusRequest::default_instance_ = NULL;

OrdersStatusRequest* OrdersStatusRequest::New() const {
  return new OrdersStatusRequest;
}

void OrdersStatusRequest::Clear() {
  logins_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool OrdersStatusRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 logins = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_logins:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8, input, this->mutable_logins())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_logins())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_logins;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void OrdersStatusRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated int32 logins = 1;
  for (int i = 0; i < this->logins_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->logins(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* OrdersStatusRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated int32 logins = 1;
  for (int i = 0; i < this->logins_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(1, this->logins(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int OrdersStatusRequest::ByteSize() const {
  int total_size = 0;

  // repeated int32 logins = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->logins_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->logins(i));
    }
    total_size += 1 * this->logins_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OrdersStatusRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const OrdersStatusRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const OrdersStatusRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void OrdersStatusRequest::MergeFrom(const OrdersStatusRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  logins_.MergeFrom(from.logins_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void OrdersStatusRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OrdersStatusRequest::CopyFrom(const OrdersStatusRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OrdersStatusRequest::IsInitialized() const {

  return true;
}

void OrdersStatusRequest::Swap(OrdersStatusRequest* other) {
  if (other != this) {
    logins_.Swap(&other->logins_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata OrdersStatusRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = OrdersStatusRequest_descriptor_;
  metadata.reflection = OrdersStatusRequest_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtoTypes

// @@protoc_insertion_point(global_scope)
